[workspace]
resolver = "3"
members = [
	"./packages/ws-protocol",
	"./packages/player-core",
	"./packages/player/src-tauri",
]
exclude = ["vendor/taskbar-lyric", "vendor/tauri-runtime-wry"]

[patch.crates-io]
tauri-runtime-wry = { path = "vendor/tauri-runtime-wry" }

[patch."https://github.com/apoint123/taskbar-lyric.git"]
taskbar-lyric = { path = "vendor/taskbar-lyric" }

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
panic = "abort"
