packages:
  - packages/*

catalog:
  "@biomejs/biome": ^2.4.16
  "@types/react": ^19.2.15
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.2
  classnames: ^2.5.1
  framer-motion: ^12.40.0
  jotai-babel: ^0.2.0
  react: ^19.2.6
  react-dom: ^19.2.6
  vite: ^8.0.14
  vite-plugin-babel: ^1.6.0
  vite-plugin-svgr: ^5.2.0
  vite-plugin-wasm: ^3.6.0
